[package]
name = "test_common"
version = "0.1.0"
authors = ["Will Smith <wds68@cornell.edu>"]
edition = "2018"

[dependencies]
thiserror = "1"
relative-path = { version = "1", features = ["serde"]  }
tempdir = "0.3"
assert_cmd = "2.0.0"
regex = "1"
lazy_static = "1"
